import Link from 'next/link';
import { AUDIENCES, FOOTER_NAV_ITEMS, SERVICES, TRADES, type Service, type Trade, type Sample } from '@/lib/data';
import { D, ICO, flowArt, heroArt } from '@/lib/illustrations';
import MobileNav from './mobile-nav';
import NavLinks from './nav-links';
import { BRAND, SITE_COPY } from '@/lib/content';
import { MotionButton, MotionItem, MotionReveal, MotionStagger } from './motion';

export function Brand(){return <Link className="brand" href="/" aria-label="PreCon Ext home"><svg className="brand-mark" viewBox="0 0 34 34" aria-hidden="true"><rect width="34" height="34" rx="3" fill="#0F2A44"/><path d="M7 25V9l10 9 10-9v16" fill="none" stroke="#F5D253" strokeWidth="2.6" strokeLinejoin="round"/><path d="M5 28h24" stroke="#B65A22" strokeWidth="2"/></svg>PRECON <span>EXT</span></Link>}
export function Header(){return <header className="site-nav"><div className="wrap nav-inner"><Brand/><MobileNav/><NavLinks/></div></header>}
export function Footer(){return <><footer className="site-foot"><div className="wrap"><div className="foot-grid"><div><div className="foot-brand">PRECON EXT</div><p className="foot-description">{BRAND.description}</p><p className="mono foot-phone">{BRAND.phone}</p><p className="mono">{BRAND.email}</p></div><div><h5>Services</h5><ul>{SERVICES.map(s=><li key={s.slug}><Link href={`/services/${s.slug}`}>{s.name}</Link></li>)}</ul></div><div><h5>Trades</h5><ul>{TRADES.slice(0,6).map(t=><li key={t.slug}><Link href={`/trades/${t.slug}`}>Div {t.div} {t.name}</Link></li>)}</ul></div><div><h5 className="sr-only">More trades</h5><ul>{TRADES.slice(6).map(t=><li key={t.slug}><Link href={`/trades/${t.slug}`}>Div {t.div} {t.name}</Link></li>)}</ul></div><div><h5>Company</h5><ul>{FOOTER_NAV_ITEMS.map(([name,href])=><li key={href}><Link href={href}>{name}</Link></li>)}</ul></div></div><div className="foot-bottom"><span>© 2026 PreCon Ext.</span><span><Link href="/privacy">Privacy Policy</Link> · <Link href="/terms">Terms &amp; Conditions</Link></span><span>Use the project request form to get started</span></div></div></footer><div className="mobile-bar"><a className="btn btn-ghost" href="tel:+18005550100">Call</a><Link className="btn btn-primary" href="/quote">{SITE_COPY.cta.primary}</Link></div></>}
export function PageHead({eyebrow,title,lede,crumb}:{eyebrow:string;title:string;lede?:string;crumb?:React.ReactNode}){return <header className="page-head"><MotionReveal className="wrap" y={18}>{crumb&&<div className="crumb">{crumb}</div>}<div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{lede&&<p className="lede">{lede}</p>}</MotionReveal></header>}
export function Svg({markup,className}:{markup:string;className?:string}){return <div className={className} aria-hidden="true" dangerouslySetInnerHTML={{__html:markup}}/>}
export function Button({href,children,dark=false}:{href:string;children:React.ReactNode;dark?:boolean}){return <MotionButton className="motion-inline"><Link className={`btn ${dark?'btn-on-dark':'btn-primary'}`} href={href}>{children}</Link></MotionButton>}
export function CTA({title,text,secondary=true}:{title:string;text:string;secondary?:boolean}){return <section className="cta-band"><MotionReveal className="wrap inner" y={18}><div><h2>{title}</h2><p>{text}</p></div><div className="btn-row"><Button href="/quote">{SITE_COPY.cta.primary}</Button>{secondary&&<MotionButton className="motion-inline"><a className="btn btn-on-dark" href="tel:+18005550100">{SITE_COPY.cta.secondary}</a></MotionButton>}</div></MotionReveal></section>}
export function ServiceCard({service,full=false}:{service:Service;full?:boolean}){return <MotionItem className="motion-fill"><Link className="card card-link" href={`/services/${service.slug}`}><div className="ico" dangerouslySetInnerHTML={{__html:ICO[service.ico as keyof typeof ICO]}}/><div className="code">{service.code}</div><h3>{service.name}</h3><p>{full?service.desc:service.short}</p>{full&&<ul>{service.points.slice(0,3).map(p=><li key={p}>{p}</li>)}</ul>}</Link></MotionItem>}
export function TradeTile({trade}:{trade:Trade}){return <MotionItem className="motion-fill"><Link className="tile" href={`/trades/${trade.slug}`}><div className="thumb"><Svg markup={D[trade.slug]()}/></div><div className="body"><span className="div">DIVISION {trade.div}</span><span className="nm">{trade.name}</span><span className="sub">{trade.short}</span></div></Link></MotionItem>}
export function Workbook({sample,tabs=['Summary','Div 03','Exclusions'],active='Div 03'}:{sample:Sample;tabs?:string[];active?:string}){return <MotionReveal className="win" y={16}><div className="win-bar"><i aria-hidden="true"/><i aria-hidden="true"/><i aria-hidden="true"/><span className="t">{sample.title} — estimate.xlsx</span></div><div className="win-tabs" aria-label="Workbook sections">{tabs.map(t=><span className={t===active?'on':''} key={t} aria-current={t===active?'page':undefined}>{t}</span>)}</div><div className="table-scroll"><table><caption className="sr-only">{sample.title} estimate sample</caption><thead><tr>{sample.cols.map((c,i)=><th className={i===1||i>=4?'n':''} key={c} scope="col">{c}</th>)}</tr></thead><tbody>{sample.rows.map((row,ri)=><tr key={ri}>{row.map((c,i)=><td className={i===1||i>=4?'n':i===3?'ref':''} key={i}>{c}</td>)}</tr>)}<tr className="total"><th scope="row" colSpan={sample.cols.length-3}>{sample.total[0]}</th><td className="n">{sample.total[1]}</td><td className="n">{sample.total[2]}</td><td className="n">{sample.total[3]}</td></tr></tbody></table></div><div className="sheet-foot"><strong>Basis:</strong> {sample.basis}</div></MotionReveal>}
export function FAQ({items,openFirst=true}:{items:[string,string][];openFirst?:boolean}){return <div className="faq">{items.map(([q,a],i)=><details open={openFirst&&i===0} key={q}><summary>{q}</summary><p>{a}</p></details>)}</div>}
export function Spec({title,unit,items}:{title:string;unit:string;items:readonly string[]}){return <div className="spec"><div className="spec-h"><h4>{title}</h4><span className="u">{unit}</span></div><ul>{items.map(i=><li key={i}><span>{i}</span></li>)}</ul></div>}
export function DarkProcess(){return <section className="band band-dark on-dark"><div className="wrap stack-lg"><MotionReveal className="stack" y={16}><div className="eyebrow">{SITE_COPY.process.eyebrow}</div><h2>{SITE_COPY.process.title}</h2></MotionReveal><MotionReveal className="flow" y={14}><Svg markup={flowArt()}/></MotionReveal><MotionStagger className="steps">{SITE_COPY.process.steps.map(([n,h,p])=><MotionItem className="step" key={n}><b>{n}</b><h4>{h}</h4><p>{p}</p></MotionItem>)}</MotionStagger></div></section>}
export { AUDIENCES, SERVICES, TRADES, heroArt };
