import Link from 'next/link';
import { TRADES } from '@/lib/data';
import { ICO, heroArt } from '@/lib/illustrations';
import { Button, CTA, DarkProcess, FAQ, ServiceSummaryCard, Svg, TradeTile, Workbook } from './components';
import { ABOUT_CONTENT, BRAND, CONTENT_SERVICES } from '@/lib/content';
import { createMetadata } from '@/lib/metadata';
export const metadata = createMetadata({ title: 'Construction decisions, made clearer.', description: 'Traceable estimating, coordinated documentation, and practical preconstruction support for contractors, subcontractors, owners, developers, and project teams.', path: '/' });
const homeFaq:[string,string][]=[['How do you make an estimate defensible?','Every quantity is tied to a drawing, scale, or stated assumption. Exclusions and open questions are visible in the deliverable, so your team can explain the number instead of guessing when a bid is reviewed.'],['What do I need to send you?','Start with the PDF plan set and specifications you have. Include the trades, project location, and important date. If the set is incomplete, say so — we will identify what needs to be confirmed.'],['How quickly can you help?','Timing depends on the size and completeness of the set. Share the bid or decision date in your request and we will confirm a practical next step after reviewing the scope.'],['How do you price the work?','We scope the work from your files and explain the fee before anything starts. You get a clear engagement rather than an open-ended subscription or software commitment.'],['What if the drawings change?','Addenda and revisions during the bid period can be coordinated with the original scope. A redesign or materially changed project after award is reviewed as new work.'],['How are project files handled?','We use the information you share to understand and respond to your request, then coordinate the agreed work. Do not send information that is not needed for the project conversation.']];
export default function Home(){return <>
<section className="hero"><div className="wrap hero-grid"><div className="stack"><div className="eyebrow">{BRAND.descriptor} · Nationwide support</div><h1>Know what you are pricing. Know what needs a decision.</h1><p className="lede">PreCon Ext helps construction teams turn moving drawings, incomplete information, and compressed deadlines into a clearer basis for action: traceable quantities, transparent pricing structure, and documentation your team can review.</p><div className="btn-row"><Button href="/quote">Send your plans</Button><Link className="btn btn-ghost" href="/services">Review our services</Link></div><div className="hero-meta"><span>TRACEABLE QUANTITIES</span><span>VISIBLE ASSUMPTIONS</span><span>RESPONSIVE PROJECT SUPPORT</span></div></div><div className="hero-art"><Svg markup={heroArt()}/></div></div></section>
<div className="wrap"><div className="stat-strip"><div className="stat"><b>01</b><small>Integrated partner</small></div><div className="stat"><b>CSI</b><small>Organized estimating</small></div><div className="stat"><b>24/7</b><small>Project support mindset</small></div><div className="stat"><b>USA</b><small>Project teams supported</small></div></div></div>
<section className="band"><div className="wrap stack-lg"><div className="stack"><div className="eyebrow">Why teams bring us in</div><h2>Useful project intelligence before the next commitment.</h2><p className="prose">The cost of unclear scope is not just rework. It is missed bid opportunities, slow approvals, and numbers no one can defend. We make the basis visible so your team can decide what to price, clarify, or carry as risk.</p></div><div className="reasons">{[['headcount','Add capacity without adding overhead','Bring in estimating and technical support when the pipeline demands it — without another salary, software seat, or fixed annual commitment.'],['volume','Move the right opportunities forward','A clear process and organized takeoffs help your team respond to more of the work that fits while protecting time for projects already underway.'],['risk','Stand behind the number','Quantities, assumptions, exclusions, and sheet references stay visible from the first review through bid day, so questions become decisions instead of delays.']].map(([icon,title,text])=><div className="reason" key={title}><div className="ico" dangerouslySetInnerHTML={{__html:ICO[icon as keyof typeof ICO]}}/><h4>{title}</h4><p>{text}</p></div>)}</div></div></section>
<section className="band band-ground"><div className="wrap stack-lg"><div className="stack"><div className="eyebrow">Services</div><h2>What we bring together</h2><p className="prose">From estimating and quantity takeoffs to drawings, engineering, visualization, and property analysis, our services connect the decisions that shape a project.</p></div><div className="grid-3">{CONTENT_SERVICES.map(s=><ServiceSummaryCard service={s} key={s.slug}/>)}</div></div></section>
<DarkProcess/>
<section className="band"><div className="wrap stack-lg"><div className="stack"><div className="eyebrow">What you receive</div><h2>A documented basis your team can use immediately.</h2><p className="prose">Not a summary number. You receive a line-item workbook, clear assumptions, written exclusions, and the references needed to review the scope, update the basis, and hand the work to the next person.</p></div><Workbook sample={TRADES[0].sample} tabs={['Summary','Div 03','Div 04','Div 05','Div 09','Exclusions']}/><div className="grid-2"><div className="stack"><h3>Every line traces back</h3><p className="prose">Quantities reference the sheet they came from, so a number questioned in a bid review takes a minute to verify rather than an afternoon.</p></div><div className="stack"><h3>Built for review and handoff</h3><p className="prose">Takeoffs can be developed in Bluebeam Revu, Planswift, or On-Screen Takeoff and delivered as editable Excel workbooks with formulas intact — ready for your review, not locked away.</p></div></div></div></section>
<section className="band band-ground"><div className="wrap stack-lg"><div className="stack"><div className="eyebrow">Trades</div><h2>Find the right estimating scope quickly.</h2><p className="prose">Each trade page shows what we measure, how it is reported, what is excluded by default, and what the delivered workbook looks like.</p></div><div className="trades">{TRADES.map(t=><TradeTile trade={t} key={t.slug}/>)}</div></div></section>
<section className="band"><div className="wrap stack-lg"><div className="stack"><div className="eyebrow">Why PreCon Ext</div><h2>{ABOUT_CONTENT.lede}</h2></div><div className="who">{ABOUT_CONTENT.benefits.slice(0,3).map(([code,title,text])=><div className="card" key={code}><div className="code">{code}</div><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
<section className="band band-ground"><div className="wrap stack-lg"><div className="stack"><div className="eyebrow">Common questions</div><h2>Before you send a set</h2></div><FAQ items={homeFaq}/></div></section><CTA title="Have a bid or project decision coming up?" text="Send the plans and scope you have. We will help identify the right next step, the information needed, and the clearest path forward."/></>}
