import Link from 'next/link';
import { TRADES } from '@/lib/data';
import { ICO, heroArt } from '@/lib/illustrations';
import { Button, CTA, DarkProcess, FAQ, Svg, TradeTile, Workbook } from './components';
import { ABOUT_CONTENT, BRAND, CONTENT_SERVICES } from '@/lib/content';
const homeFaq:[string,string][]=[['How accurate are the estimates?','[Your accuracy commitment goes here.] We document assumptions and exclusions on every estimate so the basis of the number is explicit, and we don’t price scope that isn’t drawn.'],['What do I need to send you?','A PDF plan set and specifications if you have them. Tell us which trades you need, the project location, and the bid due date. If the set is incomplete, say so — we’ll flag what we had to assume.'],['How long does it take?','[Your standard turnaround goes here.] Rush work is available depending on the size of the set and how full the schedule is that week.'],['How do you price the work?','A flat fee per project, quoted after we’ve seen the drawings and before any work starts. No subscription, no hourly billing, no software for you to buy.'],['What if the drawings change?','Addenda and revisions during the bid period are handled as part of the original engagement. A redesign after award is new scope, and we’ll quote it separately.'],['Will you sign an NDA?','[Confirm your policy here.] Plan sets and pricing you send are treated as confidential and are not shared outside the estimating team.']];
export default function Home(){return <>
<section className="hero"><div className="wrap hero-grid"><div className="stack"><div className="eyebrow">{BRAND.descriptor} · Nationwide support</div><h1>Move from project idea to construction with clarity.</h1><p className="lede">{BRAND.description}</p><div className="btn-row"><Button href="/quote">Start a project conversation</Button><Link className="btn btn-ghost" href="/services">Explore our capabilities</Link></div><div className="hero-meta"><span>ESTIMATING + TAKEOFFS</span><span>DRAWING + ENGINEERING SUPPORT</span><span>COORDINATED DELIVERABLES</span></div></div><div className="hero-art"><Svg markup={heroArt()}/></div></div></section>
<div className="wrap"><div className="stat-strip"><div className="stat"><b>01</b><small>Integrated partner</small></div><div className="stat"><b>CSI</b><small>Organized estimating</small></div><div className="stat"><b>24/7</b><small>Project support mindset</small></div><div className="stat"><b>USA</b><small>Project teams supported</small></div></div></div>
<section className="band"><div className="wrap stack-lg"><div className="stack"><div className="eyebrow">Why contractors outsource</div><h2>The estimate isn’t the bottleneck. Time is.</h2></div><div className="reasons">{[['headcount','No salary, no benefits, no software seats','A full-time estimator is a fixed annual cost whether you bid two jobs that month or twenty — before takeoff software licenses. You pay per project, quoted before we start.'],['volume','More bids out the door','Hit rates don’t change much. Bid count does. Doubling the number of qualified bids you submit is the most direct lever on revenue, and estimating capacity is what caps it.'],['risk','Quantities you can defend','Every line is tied to a sheet and a scale, with exclusions and assumptions stated up front — so when a number is questioned in a bid review, you can show where it came from.']].map(([icon,title,text])=><div className="reason" key={title}><div className="ico" dangerouslySetInnerHTML={{__html:ICO[icon as keyof typeof ICO]}}/><h4>{title}</h4><p>{text}</p></div>)}</div></div></section>
<section className="band band-ground"><div className="wrap stack-lg"><div className="stack"><div className="eyebrow">Services</div><h2>What we bring together</h2><p className="prose">From estimating and quantity takeoffs to drawings, engineering, visualization, and property analysis, our services connect the decisions that shape a project.</p></div><div className="grid-3">{CONTENT_SERVICES.map(s=><Link className="card card-link" href={`/services/${s.slug}`} key={s.slug}><div className="ico" dangerouslySetInnerHTML={{__html:ICO[s.ico as keyof typeof ICO]}}/><div className="code">{s.code}</div><h3>{s.name}</h3><p>{s.summary}</p></Link>)}</div></div></section>
<DarkProcess/>
<section className="band"><div className="wrap stack-lg"><div className="stack"><div className="eyebrow">The deliverable</div><h2>What actually lands in your inbox</h2><p className="prose">Not a summary number. A line-item workbook you can open, edit and hand to a project manager — organized the way estimators expect to read it.</p></div><Workbook sample={TRADES[0].sample} tabs={['Summary','Div 03','Div 04','Div 05','Div 09','Exclusions']}/><div className="grid-2"><div className="stack"><h3>Every line traces back</h3><p className="prose">Quantities reference the sheet they came from, so a number questioned in a bid review takes a minute to verify rather than an afternoon.</p></div><div className="stack"><h3>Built in software you already use</h3><p className="prose">Takeoffs in Bluebeam Revu, Planswift and On-Screen Takeoff. Estimates delivered as editable Excel workbooks with formulas intact — never a locked PDF.</p></div></div></div></section>
<section className="band band-ground"><div className="wrap stack-lg"><div className="stack"><div className="eyebrow">Trades</div><h2>Estimating by division</h2><p className="prose">Twelve CSI divisions, each with its own page covering exactly what we measure, in what units, and what we exclude by default.</p></div><div className="trades">{TRADES.map(t=><TradeTile trade={t} key={t.slug}/>)}</div></div></section>
<section className="band"><div className="wrap stack-lg"><div className="stack"><div className="eyebrow">Why PreCon Ext</div><h2>{ABOUT_CONTENT.lede}</h2></div><div className="who">{ABOUT_CONTENT.benefits.slice(0,3).map(([code,title,text])=><div className="card" key={code}><div className="code">{code}</div><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
<section className="band band-ground"><div className="wrap stack-lg"><div className="stack"><div className="eyebrow">Common questions</div><h2>Before you send a set</h2></div><FAQ items={homeFaq}/></div></section><CTA title="Have a bid due this week?" text="Send the set. We’ll tell you what it costs and when you’ll have it — usually the same day."/></>}
