import Link from 'next/link';
import { notFound } from 'next/navigation';
import { CONTENT_SERVICES } from '@/lib/content';
import { SERVICES } from '@/lib/data';
import { ICO } from '@/lib/illustrations';
import { CTA, PageHead, ServiceCard } from '../../components';
import { createMetadata } from '@/lib/metadata';
import type { Metadata } from 'next';

export function generateStaticParams(){return [...SERVICES.map(s=>({slug:s.slug})), ...CONTENT_SERVICES.map(s=>({slug:s.slug}))];}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{
  const {slug}=await params;
  const content=CONTENT_SERVICES.find(s=>s.slug===slug);
  const legacy=SERVICES.find(s=>s.slug===slug);
  const item=content ? { name: content.name, summary: content.summary } : legacy ? { name: legacy.name, summary: legacy.short } : null;
  return createMetadata({ title: item ? item.name : 'Service not found', description: item ? item.summary : 'Explore PreCon Ext project support services.', path: `/services/${slug}` });
}

export default async function ServicePage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;
  const content=CONTENT_SERVICES.find(s=>s.slug===slug);
  const legacy=SERVICES.find(s=>s.slug===slug);
  if(!content&&!legacy) notFound();
  if(content) return <><PageHead eyebrow={`${content.code} · Service`} title={content.name} lede={content.summary} crumb={<><Link href="/services">Services</Link> / {content.name}</>}/><section className="band"><div className="wrap stack-lg"><div className="split" style={{alignItems:'start'}}><div className="stack"><div className="ico" style={{width:64,height:64}} dangerouslySetInnerHTML={{__html:ICO[content.ico as keyof typeof ICO]}}/><div className="code">{content.code}</div><h2 style={{fontSize:'var(--s2)'}}>What this supports</h2><p className="prose">{content.details}</p><h3>Best fit when</h3><p className="prose">You have a defined project question, a working set of information, and need a reviewable deliverable that helps the next person price, coordinate, approve, or act.</p></div><div className="spec"><div className="spec-h"><h4>Included work</h4><span className="u">SCOPE</span></div><ul>{content.points.map(p=><li key={p}><span>{p}</span></li>)}</ul></div></div><div className="grid-2"><div className="spec"><div className="spec-h"><h4>How the work moves</h4><span className="u">PROCESS</span></div><ul><li><span>Review the set, scope, location, and decision date</span></li><li><span>Confirm assumptions, exclusions, and the useful output</span></li><li><span>Develop and organize the agreed package</span></li><li><span>Review questions and revisions with a clear record</span></li></ul></div><div className="spec"><div className="spec-h"><h4>What affects scope</h4><span className="u">INPUTS</span></div><ul><li><span>Plan and specification completeness</span></li><li><span>Project stage and jurisdiction</span></li><li><span>Required level of detail and format</span></li><li><span>Addenda, alternates, and decision deadline</span></li></ul></div></div><div className="stack"><div className="eyebrow">Related services</div><div className="grid-2">{CONTENT_SERVICES.filter(s=>s.slug!==content.slug).slice(0,4).map(s=><Link className="card card-link" href={`/services/${s.slug}`} key={s.slug}><div className="ico" dangerouslySetInnerHTML={{__html:ICO[s.ico as keyof typeof ICO]}}/><div className="code">{s.code}</div><h3>{s.name}</h3><p>{s.summary}</p><span className="card-action">Review this service →</span></Link>)}</div></div></div></section><CTA title={`Discuss ${content.name.toLowerCase()}`} text="Send the project information you have and we will define the useful scope, open questions, and next step." /></>;
  return <><PageHead eyebrow={`${legacy!.code} · Service`} title={legacy!.name} lede={legacy!.short} crumb={<><Link href="/services">Services</Link> / {legacy!.name}</>}/><section className="band"><div className="wrap stack-lg"><div className="split" style={{alignItems:'start'}}><div className="stack"><h2 style={{fontSize:'var(--s2)'}}>What this supports</h2><p className="prose">{legacy!.desc}</p><h3>Best fit when</h3><p className="prose">{legacy!.who}</p></div><div className="spec"><div className="spec-h"><h4>Included work</h4><span className="u">SCOPE</span></div><ul>{legacy!.points.map(p=><li key={p}><span>{p}</span></li>)}</ul></div></div><div className="grid-2"><div className="spec"><div className="spec-h"><h4>How the work moves</h4><span className="u">PROCESS</span></div><ul><li><span>Review the project set and decision date</span></li><li><span>Confirm the useful output and assumptions</span></li><li><span>Build and organize the agreed package</span></li><li><span>Review questions and revisions</span></li></ul></div><div className="spec"><div className="spec-h"><h4>What affects scope</h4><span className="u">INPUTS</span></div><ul><li><span>Completeness of the information provided</span></li><li><span>Required detail, format, and jurisdiction</span></li><li><span>Addenda, alternates, and revisions</span></li><li><span>Decision deadline and review path</span></li></ul></div></div><div className="grid-2">{SERVICES.filter(x=>x.slug!==legacy!.slug).map(o=><ServiceCard service={o} key={o.slug}/>)}</div></div></section><CTA title={`Need ${legacy!.name.toLowerCase()}?`} text="Send the project information and we will come back with a clear scope and next step." /></>;
}
